[package]
name = "test_lmm"
version = "0.1.0"
edition = "2021"

[dependencies]
kalosm = { version = "0.3.2", features = ["language", "vision" , "sound"] }
tokio = { version = "1.40.0", features = ["full"] }
futures-util = "0.3.30"
image = "0.24.9"
rwuerstchen = "0.3.2"


